FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN HUSKY=0 pnpm install --frozen-lockfile --shamefully-hoist

EXPOSE 8000

CMD ["pnpm", "start:dev"]
